# Server configuration file
# python:
#   file_path: ImageProcessingUnit\main.py
#   command: python
#   port: 3000
python:
  working_directory: \
  command: python
  file_name: 'main.py'
node:
  working_directory: RecommendationsUnit\
  command: npm
  argument_1: run
  argument_2: dev
