module.exports = {
    MAX_GOAL_PASSING_DISTANCE: 290,
    MIN_GOAL_PASSING_DISTANCE: 20,
    MAX_TEAMMATE_PASSING_DISTANCE: 290,
    MIN_TEAMMATE_PASSING_DISTANCE: 20,
    MAX_OPPONENT_DISTANCE: 10
}