module.exports = {
    MAX_GOAL_PASSING_DISTANCE: 250,
    MIN_GOAL_PASSING_DISTANCE: 10,
    MAX_TEAMMATE_PASSING_DISTANCE: 150,
    MIN_TEAMMATE_PASSING_DISTANCE: 10,
    MAX_OPPONENT_DISTANCE: 10
}

// module.exports = {
//     MAX_GOAL_PASSING_DISTANCE: 1000,
//     MIN_GOAL_PASSING_DISTANCE: 10,
//     MAX_TEAMMATE_PASSING_DISTANCE: 1000,
//     MIN_TEAMMATE_PASSING_DISTANCE: 10,
//     MAX_OPPONENT_DISTANCE: 10
// }